---

- name: "Loop test"
  hosts: us
  gather_facts: true
  connection: network_cli

  tasks:
    - name: "Loop through IP info"
      debug:
        # https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_facts_module.html
        msg: "{{ ansible_facts }}"
        #msg: "{{ ansible_facts['net_hostname'] }}"
        #msg: "{{ ansible_facts['net_hostname'] }} has an IP address of : {{ item }} configured"
      #loop: "{{ ansible_facts['net_all_ipv4_address'] }}"