---

- name: "Print var info"
  hosts: all
  gather_facts: no

  tasks:
    - name: "Display vars"
      debug:
        # hostvars is used to access information about hosts in inventory
        msg: "{{ hostvars[ansible_host] }}"   