---

- name: "Play 1"
  hosts: localhost

  tasks:
    - name: "Task 1 of Play 1 Collect facts about local host"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"
      register: output

    - name: "Task 2 of Play 1 -  Recording Variables"
      set_fact:
        TD: "{{ ansible_date_time.date }}"

    - name: "Task 3 of Play 1 - Creating Directories"
      file: 
        path: "Backups/{{ TD }}"
        state: directory
      run_once: true
    
- name: "Play 2"
  hosts: all 
  connection: network_cli

  tasks:
    - name: "Task 1 of Play 2 - Pull Configuration From Remote Devices"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["config"]
      register: result       

    # Debug task
    #- name: "Print"
    #  debug:
    #    msg: "{{ result }}"
  
    - name: "Task 2 of Play 2: Create Startup Config Subdirectory"
      file:
        path: "Backups/{{ hostvars.localhost.TD }}/startup-configs"
        state: directory
      run_once: true

    - name: "Task 3 of Play 2: Create Running Config Subdirectory"
      file:
        path: "Backups/{{ hostvars.localhost.TD }}/running-configs"
        state: directory
      run_once: true
    
    - name: "Task 4 of Play 2: Copy Startup Configs to Disk"
      copy:
        content: "{{ result.ansible_facts.napalm_config.startup }}"
        dest: "Backups/{{ hostvars.localhost.TD }}/startup-configs/{{ inventory_hostname }}-startup-config.txt"

    - name: "Task 5 of Play 2: Copy Running Configs to Disk"
      copy:
        content: "{{ result.ansible_facts.napalm_config.running }}"
        dest: "Backups/{{ hostvars.localhost.TD }}/running-configs/{{ inventory_hostname }}-running-config.txt"
