---
# Variables from host_vars will always take precedence over variables from less granular origins, such as group_vars etc. !!

BGP:
  ASN: "65001"
  peers: 
    - neighbor: "10.0.0.2"
      peer_asn: "65002"

    - neighbor: "10.0.0.13"
      peer_asn: "13"

    - neighbor: "192.168.66.1"
      peer_asn: "661"

eigrp_style: "named"
eigrp: 
  asn: "1"